name: Generate Snake

on:
  schedule:
    # Runs at 12am UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: generate snake.svg
        uses: Platane/snk@v2
        with:
          github_user_name: JoeyIsNotRobot
          outputs: dist/snake.svg
      - name: push snake.svg to the output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          file: dist/snake.svg
